[tool.pyright]
typeCheckingMode = "off"

[project]
name = "locllm"
version = "0.1.0"
description = "Model Service API - For local serving of the models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coverage>=7.8.2",
    "pytest>=8.4.0",
    "transformers>=4.52.4",
]
