name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Generate Pylint Badge
      run: |
        PYLINT_SCORE=$(pylint $(git ls-files '*.py') | grep -Po '(?<=rated at )[0-9\.]+' || echo "0")
        echo "PYLINT_SCORE=$PYLINT_SCORE" >> $GITHUB_ENV
        echo "### Pylint Score: $PYLINT_SCORE/10" >> $GITHUB_STEP_SUMMARY
    - name: Create Pylint Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: YOUR_GIST_ID # You'll need to create a gist and add its ID here
        filename: pylint-badge.json
        label: pylint
        message: ${{ env.PYLINT_SCORE }}/10
        color: ${{ env.PYLINT_SCORE >= 9 && 'brightgreen' || env.PYLINT_SCORE >= 7 && 'yellow' || 'red' }}