name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run Pylint
      run: |
        # Run pylint and save output
        pylint $(git ls-files '*.py') > pylint_output.txt || true
        
        # Extract score and save to summary
        PYLINT_SCORE=$(cat pylint_output.txt | grep -Po '(?<=rated at )[0-9\.]+' || echo "0")
        echo "### Pylint Score: $PYLINT_SCORE/10" >> $GITHUB_STEP_SUMMARY
        
        # Add score to job summary
        echo "Pylint Score: $PYLINT_SCORE/10" >> $GITHUB_STEP_SUMMARY
        
        # Optional: Print full pylint output to the job summary
        echo "### Detailed Pylint Output" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat pylint_output.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY